'use client'

import {
  CircleAlert as AlertCircle,
  Check,
  ChevronLeft,
  ChevronRight,
  Save,
  Sparkle as Sparkles,
} from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

import { LineItemsTable } from '@/components/finance/line-items-table'
import { MaintenanceOfferEditor } from '@/components/proposals/maintenance-offer-editor'
import { PaymentPlanEditor } from '@/components/proposals/payment-plan-editor'
import { ProblemSolutionEditor } from '@/components/proposals/problem-solution-editor'
import { ScopeModulesEditor } from '@/components/proposals/scope-modules-editor'
import { AiNotice } from '@/components/ui/ai-notice'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { FormFeedback, useFormFeedback } from '@/components/ui/form-feedback'
import { FormRow } from '@/components/ui/form-row'
import { Input } from '@/components/ui/input'
import { Markdown } from '@/components/ui/markdown'
import { Select } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { VersionConflictDialog } from '@/components/ui/version-conflict-dialog'
import { computeProposalTotals, EMPTY_LINE_ITEM, type LineItem } from '@/lib/finance'
import {
  createEmptyPair,
  type EditableKeyPoint,
  type EditablePair,
  serializeKeyPoints,
  unzipPairs,
  zipKeyPoints,
} from '@/lib/proposals/key-points'
import {
  DEFAULT_MAINTENANCE_OFFER,
  type MaintenanceOffer,
  selectedMaintenancePlan,
} from '@/lib/proposals/maintenance'
import {
  DEFAULT_CHANGE_MANAGEMENT_TERMS,
  PAYMENT_SCHEDULE_LABELS,
  PAYMENT_SCHEDULE_TEMPLATES,
  paymentPlanForSchedule,
  type PaymentPlanItem,
  type PaymentSchedule,
  type ScopeModule,
} from '@/lib/proposals/scope'
import { formatEUR } from '@/lib/utils'

import { setProposalTeamMembers, updateProposal } from '../actions'

export type EditableItem = LineItem

const EDITOR_STEPS = [
  { label: 'Datos', description: 'Base de la propuesta' },
  { label: 'Alcance', description: 'Qué vamos a entregar' },
  { label: 'Precio', description: 'Partidas y condiciones' },
  { label: 'Revisión', description: 'Equipo y comprobación final' },
] as const

type ProposalTeamMember = { id: string; name: string; job_title: string | null }

export type ProposalEditorProps = {
  id: string
  initialTitle: string
  initialValidUntil: string | null
  initialNotes: string | null
  initialContextMarkdown: string | null
  initialProblems: EditableKeyPoint[]
  initialSolutions: EditableKeyPoint[]
  initialTerms: string | null
  initialScopeModules: ScopeModule[]
  initialDeliverables: string | null
  initialAcceptanceCriteria: string | null
  initialPaymentSchedule: PaymentSchedule | null
  initialPaymentPlan: PaymentPlanItem[]
  initialPaymentTerms: string | null
  initialChangeManagementTerms: string | null
  initialMaintenanceOptions: MaintenanceOffer | null
  initialMaintenanceSelectedPlanId: string | null
  teamMembers: ProposalTeamMember[]
  initialTeamMemberIds: string[]
  initialItems: EditableItem[]
  /** Optimistic-concurrency token captured with the record. */
  initialVersion: number
  /** When true, fields are read-only (proposal accepted/rejected). */
  locked: boolean
  /** Gates the "generate problems/solutions with AI" affordance. */
  aiEnabled: boolean
  /** The lead whose CRM briefing can be used to prepare this proposal. */
  leadId: string | null
  /** Runs once when arriving from the "Crear y prerrellenar" flow. */
  autoGenerateDraft: boolean
}

/**
 * Inline editor for the proposal detail page. Changes remain local until the
 * user explicitly saves them, avoiding partial or conflicting writes.
 *
 * Narrative is split into three blocks (context / problems / solutions) that
 * map 1-to-1 to deck slides and portal sections; see
 * `lib/proposals/key-points.ts` for the wire shape.
 */
export function ProposalEditor({
  id,
  initialTitle,
  initialValidUntil,
  initialNotes,
  initialContextMarkdown,
  initialProblems,
  initialSolutions,
  initialTerms,
  initialScopeModules,
  initialDeliverables,
  initialAcceptanceCriteria,
  initialPaymentSchedule,
  initialPaymentPlan,
  initialPaymentTerms,
  initialChangeManagementTerms,
  initialMaintenanceOptions,
  initialMaintenanceSelectedPlanId,
  teamMembers,
  initialTeamMemberIds,
  initialItems,
  initialVersion,
  locked,
  aiEnabled,
  leadId,
  autoGenerateDraft,
}: ProposalEditorProps) {
  const router = useRouter()
  const [expectedVersion, setExpectedVersion] = useState(initialVersion)
  const [conflictOpen, setConflictOpen] = useState(false)
  const [title, setTitle] = useState(initialTitle)
  const [validUntil, setValidUntil] = useState(initialValidUntil ?? '')
  const [notes, setNotes] = useState(initialNotes ?? '')
  const [notesPreview, setNotesPreview] = useState(false)
  const [contextMarkdown, setContextMarkdown] = useState(initialContextMarkdown ?? '')
  const [pairs, setPairs] = useState<EditablePair[]>(() =>
    zipKeyPoints(initialProblems, initialSolutions),
  )
  const [generating, setGenerating] = useState(false)
  const aiFeedback = useFormFeedback()
  const saveFeedback = useFormFeedback({ successResetMs: 4_000 })
  const automaticDraftStarted = useRef(false)
  const [terms, setTerms] = useState(initialTerms ?? '')
  const [scopeModules, setScopeModules] = useState(initialScopeModules)
  const [deliverables, setDeliverables] = useState(initialDeliverables ?? '')
  const [acceptanceCriteria, setAcceptanceCriteria] = useState(initialAcceptanceCriteria ?? '')
  const [paymentSchedule, setPaymentSchedule] = useState<PaymentSchedule>(
    initialPaymentSchedule ?? 'half_half',
  )
  const [paymentPlan, setPaymentPlan] = useState<PaymentPlanItem[]>(
    initialPaymentPlan.length > 0
      ? initialPaymentPlan
      : paymentPlanForSchedule(initialPaymentSchedule ?? 'half_half'),
  )
  const [paymentTerms, setPaymentTerms] = useState(
    initialPaymentTerms ?? PAYMENT_SCHEDULE_TEMPLATES.half_half,
  )
  const [changeManagementTerms, setChangeManagementTerms] = useState(
    initialChangeManagementTerms ?? DEFAULT_CHANGE_MANAGEMENT_TERMS,
  )
  const [maintenanceOptions, setMaintenanceOptions] = useState<MaintenanceOffer>(
    initialMaintenanceOptions ?? DEFAULT_MAINTENANCE_OFFER,
  )
  const [maintenanceSelectedPlanId, setMaintenanceSelectedPlanId] = useState<string | null>(
    initialMaintenanceSelectedPlanId,
  )
  const [teamMemberIds, setTeamMemberIds] = useState(initialTeamMemberIds)
  const [activeStep, setActiveStep] = useState(0)
  const [items, setItems] = useState<EditableItem[]>(
    initialItems.length > 0
      ? initialItems.map((it) => ({ ...it, id: it.id || crypto.randomUUID() }))
      : [{ ...EMPTY_LINE_ITEM, id: crypto.randomUUID() } as EditableItem],
  )

  const payload = useMemo(() => {
    const { problems, solutions } = unzipPairs(pairs)
    return {
      id,
      expected_version: expectedVersion,
      title,
      valid_until: validUntil || null,
      notes: notes || null,
      context_markdown: contextMarkdown || null,
      problems: serializeKeyPoints(problems),
      solutions: serializeKeyPoints(solutions),
      terms: terms || null,
      scope_modules: scopeModules.length > 0 ? scopeModules : null,
      deliverables: deliverables || null,
      acceptance_criteria: acceptanceCriteria || null,
      payment_schedule: paymentSchedule,
      payment_plan: paymentPlan,
      payment_terms: paymentTerms || null,
      change_management_terms: changeManagementTerms || null,
      maintenance_options: maintenanceOptions,
      maintenance_selected_plan_id: maintenanceSelectedPlanId,
      items,
    }
  }, [
    id,
    expectedVersion,
    title,
    validUntil,
    notes,
    contextMarkdown,
    pairs,
    terms,
    scopeModules,
    deliverables,
    acceptanceCriteria,
    paymentSchedule,
    paymentPlan,
    paymentTerms,
    changeManagementTerms,
    maintenanceOptions,
    maintenanceSelectedPlanId,
    items,
  ])

  async function handleGenerateNarrative() {
    setGenerating(true)
    aiFeedback.setPending()
    try {
      const res = await fetch(`/api/proposals/${id}/generate-narrative`, { method: 'POST' })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? 'No se pudo generar la narrativa.')
      const incoming = (json.pairs ?? []) as Array<Omit<EditablePair, 'id'>>
      setPairs(incoming.map((p) => ({ ...createEmptyPair(), ...p })))
      aiFeedback.setSuccess('Narrativa generada')
    } catch (err) {
      aiFeedback.setError(err instanceof Error ? err.message : 'Error desconocido')
    } finally {
      setGenerating(false)
    }
  }

  const narrativeIsEmpty =
    !notes.trim() && !contextMarkdown.trim() && pairs.length === 0 && !terms.trim()
  const commercialScopeIsEmpty =
    scopeModules.length === 0 && !deliverables.trim() && !acceptanceCriteria.trim()
  const hasEmptyDraftFields =
    narrativeIsEmpty ||
    commercialScopeIsEmpty ||
    !paymentTerms.trim() ||
    !changeManagementTerms.trim()
  const saveErrors =
    saveFeedback.state.status === 'error'
      ? saveFeedback.state.message.split('\n').filter(Boolean)
      : []
  const proposalTotals = useMemo(() => computeProposalTotals(items), [items])
  const selectedMaintenance = selectedMaintenancePlan(maintenanceOptions, maintenanceSelectedPlanId)
  const stepComplete = [
    Boolean(title.trim() && validUntil),
    Boolean(contextMarkdown.trim() || pairs.length || scopeModules.length || deliverables.trim()),
    Boolean(items.some((item) => item.description.trim() && Number(item.quantity) > 0)),
    !maintenanceOptions.enabled || Boolean(selectedMaintenance),
  ]
  const currentStep = EDITOR_STEPS[activeStep] ?? EDITOR_STEPS[0]!
  const nextStep = EDITOR_STEPS[activeStep + 1] ?? currentStep

  async function handleSave() {
    saveFeedback.setPending()
    try {
      const result = await updateProposal(payload)
      if (!result.ok) {
        if (result.code === 'conflict') setConflictOpen(true)
        else saveFeedback.setError(result.error)
        return
      }
      const teamResult = await setProposalTeamMembers({
        proposal_id: id,
        member_ids: teamMemberIds,
      })
      if (!teamResult.ok) {
        setExpectedVersion(result.version)
        saveFeedback.setError(
          `La propuesta se guardó, pero no se pudo actualizar el equipo: ${teamResult.error}`,
        )
        return
      }
      setExpectedVersion(result.version)
      saveFeedback.setSuccess('Propuesta guardada')
      router.push(`/proposals/${id}`)
    } catch (error) {
      saveFeedback.setError(
        error instanceof Error ? error.message : 'No se pudo guardar la propuesta',
      )
    }
  }

  function handlePaymentScheduleChange(value: PaymentSchedule) {
    setPaymentSchedule(value)
    if (value !== 'custom') setPaymentTerms(PAYMENT_SCHEDULE_TEMPLATES[value])
    setPaymentPlan(paymentPlanForSchedule(value))
  }

  const handleGenerateDraft = useCallback(async () => {
    if (!leadId || generating || locked || !hasEmptyDraftFields) return
    setGenerating(true)
    aiFeedback.setPending()
    try {
      const res = await fetch(`/api/proposals/${id}/generate-draft`, { method: 'POST' })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? 'No se pudo preparar la propuesta.')

      const incoming = (json.pairs ?? []) as Array<Omit<EditablePair, 'id'>>
      const nextPairs = incoming.map((pair) => ({ ...createEmptyPair(), ...pair }))
      const nextScopeModules = (json.scope_modules ?? []) as ScopeModule[]
      const titleIsEmpty = !title.trim()
      const notesAreEmpty = !notes.trim()
      const contextIsEmpty = !contextMarkdown.trim()
      const pairsAreEmpty = pairs.length === 0
      const termsAreEmpty = !terms.trim()
      const modulesAreEmpty = scopeModules.length === 0
      const deliverablesAreEmpty = !deliverables.trim()
      const acceptanceCriteriaAreEmpty = !acceptanceCriteria.trim()
      const paymentTermsAreEmpty = !paymentTerms.trim()
      const changeManagementTermsAreEmpty = !changeManagementTerms.trim()
      if (titleIsEmpty) setTitle(json.title)
      if (notesAreEmpty) setNotes(json.notes ?? '')
      if (contextIsEmpty) setContextMarkdown(json.context_markdown ?? '')
      if (pairsAreEmpty) setPairs(nextPairs)
      if (termsAreEmpty) setTerms(json.terms ?? '')
      if (modulesAreEmpty && nextScopeModules.length > 0) setScopeModules(nextScopeModules)
      if (deliverablesAreEmpty) setDeliverables(json.deliverables ?? '')
      if (acceptanceCriteriaAreEmpty) setAcceptanceCriteria(json.acceptance_criteria ?? '')
      if (paymentTermsAreEmpty) {
        setPaymentSchedule(json.payment_schedule as PaymentSchedule)
        setPaymentTerms(json.payment_terms ?? '')
      }
      if (changeManagementTermsAreEmpty) {
        setChangeManagementTerms(json.change_management_terms ?? '')
      }
      aiFeedback.setSuccess('Borrador preparado con el contexto del lead')
    } catch (err) {
      aiFeedback.setError(err instanceof Error ? err.message : 'Error desconocido')
    } finally {
      setGenerating(false)
    }
  }, [
    acceptanceCriteria,
    aiFeedback,
    changeManagementTerms,
    contextMarkdown,
    deliverables,
    generating,
    hasEmptyDraftFields,
    id,
    leadId,
    locked,
    notes,
    pairs,
    paymentTerms,
    scopeModules,
    terms,
    title,
  ])

  useEffect(() => {
    if (
      !autoGenerateDraft ||
      !aiEnabled ||
      !leadId ||
      locked ||
      !narrativeIsEmpty ||
      !commercialScopeIsEmpty ||
      automaticDraftStarted.current
    ) {
      return
    }
    automaticDraftStarted.current = true
    void handleGenerateDraft()
  }, [
    autoGenerateDraft,
    aiEnabled,
    leadId,
    locked,
    narrativeIsEmpty,
    commercialScopeIsEmpty,
    handleGenerateDraft,
  ])

  return (
    <>
      <div className="flex flex-col gap-5">
        <header className="border-border bg-background/95 sticky top-3 z-20 flex flex-wrap items-center gap-3 rounded-xl border p-3 shadow-sm backdrop-blur">
          <div className="min-w-0 flex-1">
            <p className="text-muted-foreground mb-1 text-[11px] font-medium tracking-wide uppercase">
              Paso {activeStep + 1} de {EDITOR_STEPS.length} · {currentStep.label}
            </p>
            <Input
              value={title}
              onChange={(event) => setTitle(event.target.value)}
              disabled={locked}
              placeholder="Título de la propuesta"
              className="h-9 text-base font-medium"
              aria-label="Título"
            />
          </div>
          {!locked ? (
            <div className="flex items-center gap-3">
              <FormFeedback state={saveFeedback.state} pendingLabel="Guardando propuesta…" />
              <Button onClick={handleSave} disabled={saveFeedback.pending}>
                <Save className="size-4" aria-hidden />
                {saveFeedback.pending ? 'Guardando…' : 'Guardar y ver propuesta'}
              </Button>
            </div>
          ) : null}
        </header>

        {saveFeedback.state.status === 'error' && saveErrors.length > 0 ? (
          <Alert variant="destructive" className="border-destructive/30 bg-destructive/5 px-4 py-3">
            <AlertCircle className="size-4" aria-hidden />
            <AlertTitle>No se ha podido guardar la propuesta</AlertTitle>
            <AlertDescription>
              <p>Revisa y corrige estos campos. Tus cambios siguen en esta pantalla.</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                {saveErrors.map((error) => (
                  <li key={error}>{error}</li>
                ))}
              </ul>
            </AlertDescription>
          </Alert>
        ) : null}

        <nav
          aria-label="Pasos de la propuesta"
          className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"
        >
          {EDITOR_STEPS.map((step, index) => {
            const active = activeStep === index
            return (
              <button
                key={step.label}
                type="button"
                onClick={() => setActiveStep(index)}
                aria-current={active ? 'step' : undefined}
                className={`flex items-center gap-3 rounded-lg border p-3 text-left transition-colors ${active ? 'border-primary bg-primary/5' : 'border-border bg-card hover:bg-muted/40'}`}
              >
                <span
                  className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs font-semibold ${stepComplete[index] ? 'bg-primary text-primary-foreground' : active ? 'border-primary text-primary border' : 'bg-muted text-muted-foreground'}`}
                >
                  {stepComplete[index] ? <Check className="size-3.5" aria-hidden /> : index + 1}
                </span>
                <span className="min-w-0">
                  <span className="block text-sm font-semibold">{step.label}</span>
                  <span className="text-muted-foreground block truncate text-[11px]">
                    {step.description}
                  </span>
                </span>
              </button>
            )
          })}
        </nav>

        <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_18rem]">
          <main className="min-w-0">
            {activeStep === 0 ? (
              <section className="border-border bg-card flex flex-col gap-5 rounded-xl border p-5">
                <header>
                  <h2 className="text-base font-semibold">Empieza por lo esencial</h2>
                  <p className="text-muted-foreground mt-1 text-sm">
                    Define la vigencia y añade solo las notas que necesites para preparar la
                    propuesta.
                  </p>
                </header>

                {aiEnabled && leadId && hasEmptyDraftFields && !locked ? (
                  <div className="border-primary/20 bg-primary/5 flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4">
                    <div>
                      <p className="text-sm font-medium">Prepara una primera versión con IA</p>
                      <p className="text-muted-foreground mt-1 text-xs">
                        Usa el historial del lead y rellena solo los campos que estén vacíos.
                      </p>
                    </div>
                    <Button
                      type="button"
                      variant="outline"
                      disabled={generating}
                      onClick={handleGenerateDraft}
                    >
                      <Sparkles className="size-4" aria-hidden />
                      {generating ? 'Preparando…' : 'Crear borrador'}
                    </Button>
                  </div>
                ) : null}

                <div className="grid gap-5 lg:grid-cols-[minmax(0,0.6fr)_minmax(0,1.4fr)]">
                  <FormRow
                    label="Válida hasta"
                    htmlFor="valid-until"
                    hint="Fecha límite para aceptar esta propuesta."
                  >
                    <Input
                      id="valid-until"
                      type="date"
                      value={validUntil}
                      onChange={(event) => setValidUntil(event.target.value)}
                      disabled={locked}
                    />
                  </FormRow>
                  <div className="flex flex-col gap-1.5">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium">Notas</span>
                      {notes ? (
                        <button
                          type="button"
                          onClick={() => setNotesPreview((preview) => !preview)}
                          className="text-muted-foreground hover:text-foreground text-xs transition-colors"
                        >
                          {notesPreview ? 'Editar' : 'Previsualizar'}
                        </button>
                      ) : null}
                    </div>
                    {notesPreview && notes ? (
                      <div className="border-border bg-muted/20 min-h-32 rounded-md border px-3 py-2">
                        <Markdown source={notes} />
                      </div>
                    ) : (
                      <Textarea
                        id="notes"
                        value={notes}
                        onChange={(event) => setNotes(event.target.value)}
                        disabled={locked}
                        rows={5}
                        placeholder="Notas internas o para el cliente… (soporta Markdown)"
                      />
                    )}
                  </div>
                </div>
              </section>
            ) : null}

            {activeStep === 1 ? (
              <div className="flex flex-col gap-5">
                <section className="border-border bg-card flex flex-col gap-4 rounded-xl border p-5">
                  <header className="flex items-start justify-between gap-3">
                    <div>
                      <h2 className="text-base font-semibold">Cuenta la propuesta</h2>
                      <p className="text-muted-foreground mt-1 text-sm">
                        Explica el punto de partida y cómo lo vas a resolver.
                      </p>
                    </div>
                    <div className="flex shrink-0 items-center gap-2">
                      <FormFeedback state={aiFeedback.state} pendingLabel="Generando…" />
                      {!aiEnabled ? <AiNotice inline /> : null}
                    </div>
                  </header>
                  <FormRow
                    label="Contexto"
                    htmlFor="context-markdown"
                    hint="Resume la situación actual del cliente en 2-3 frases."
                  >
                    <Textarea
                      id="context-markdown"
                      value={contextMarkdown}
                      onChange={(event) => setContextMarkdown(event.target.value)}
                      disabled={locked}
                      rows={4}
                      placeholder="Tras nuestras conversaciones, hemos detectado que…"
                    />
                  </FormRow>
                  <FormRow
                    label="Problemas y soluciones"
                    htmlFor="problems-solutions"
                    hint="Cada problema se mostrará junto a su solución."
                  >
                    <ProblemSolutionEditor
                      items={pairs}
                      onChange={setPairs}
                      locked={locked}
                      aiEnabled={aiEnabled}
                      onGenerate={handleGenerateNarrative}
                      generating={generating}
                    />
                  </FormRow>
                </section>

                <section className="border-border bg-card flex flex-col gap-4 rounded-xl border p-5">
                  <header>
                    <h2 className="text-base font-semibold">Alcance y entregables</h2>
                    <p className="text-muted-foreground mt-1 text-sm">
                      Añade los módulos y concreta lo que recibirá el cliente.
                    </p>
                  </header>
                  <ScopeModulesEditor
                    modules={scopeModules}
                    onChange={setScopeModules}
                    locked={locked}
                  />
                  <FormRow
                    label="Entregables"
                    htmlFor="deliverables"
                    hint="Qué recibirá el cliente al finalizar."
                  >
                    <Textarea
                      id="deliverables"
                      value={deliverables}
                      onChange={(event) => setDeliverables(event.target.value)}
                      disabled={locked}
                      rows={4}
                      placeholder="- Diseño validado\n- Desarrollo de los módulos acordados\n- Formación y documentación"
                    />
                  </FormRow>
                  <details className="border-border bg-muted/20 rounded-lg border p-3">
                    <summary className="cursor-pointer text-sm font-medium">
                      Añadir criterios de aceptación
                    </summary>
                    <div className="mt-3">
                      <FormRow
                        label="Criterios de aceptación"
                        htmlFor="acceptance-criteria"
                        hint="Cómo comprobaremos que el trabajo está entregado."
                      >
                        <Textarea
                          id="acceptance-criteria"
                          value={acceptanceCriteria}
                          onChange={(event) => setAcceptanceCriteria(event.target.value)}
                          disabled={locked}
                          rows={4}
                          placeholder="- Los flujos descritos funcionan en producción.\n- El cliente valida los entregables acordados."
                        />
                      </FormRow>
                    </div>
                  </details>
                </section>
              </div>
            ) : null}

            {activeStep === 2 ? (
              <div className="flex flex-col gap-5">
                <section className="border-border bg-card flex flex-col gap-4 rounded-xl border p-5">
                  <header>
                    <h2 className="text-base font-semibold">Precio de la propuesta</h2>
                    <p className="text-muted-foreground mt-1 text-sm">
                      Añade una partida por cada servicio. Los totales se calculan automáticamente.
                    </p>
                  </header>
                  <div className="border-border min-w-0 overflow-hidden rounded-lg border">
                    <LineItemsTable
                      items={items}
                      onChange={setItems}
                      locked={locked}
                      showBillingCycle
                    />
                  </div>
                </section>

                <section className="border-border bg-card flex flex-col gap-4 rounded-xl border p-5">
                  <header>
                    <h2 className="text-base font-semibold">Forma de pago</h2>
                    <p className="text-muted-foreground mt-1 text-sm">
                      Elige una base y ajusta el mensaje para el cliente si lo necesitas.
                    </p>
                  </header>
                  <FormRow label="Calendario de pago" htmlFor="payment-schedule">
                    <div className="flex flex-col gap-3">
                      <Select
                        id="payment-schedule"
                        value={paymentSchedule}
                        onChange={(event) =>
                          handlePaymentScheduleChange(event.target.value as PaymentSchedule)
                        }
                        disabled={locked}
                      >
                        {Object.entries(PAYMENT_SCHEDULE_LABELS).map(([value, label]) => (
                          <option key={value} value={value}>
                            {label}
                          </option>
                        ))}
                      </Select>
                      <Textarea
                        value={paymentTerms}
                        onChange={(event) => setPaymentTerms(event.target.value)}
                        disabled={locked}
                        rows={4}
                        placeholder="Condiciones de pago"
                        aria-label="Condiciones de pago"
                      />
                    </div>
                  </FormRow>
                  <div className="border-border bg-muted/20 rounded-lg border p-3">
                    <p className="mb-1 text-sm font-medium">Facturación por plazos</p>
                    <p className="text-muted-foreground mb-3 text-xs">
                      Personaliza los cobros que se prepararán como borradores al aceptar la
                      propuesta.
                    </p>
                    <PaymentPlanEditor
                      plan={paymentPlan}
                      total={proposalTotals.oneTime.total}
                      onChange={setPaymentPlan}
                      locked={locked}
                    />
                  </div>
                  <details className="border-border bg-muted/20 rounded-lg border p-3">
                    <summary className="cursor-pointer text-sm font-medium">
                      Personalizar condiciones
                    </summary>
                    <div className="mt-4 grid gap-4 lg:grid-cols-2">
                      <FormRow label="Gestión de cambios" htmlFor="change-management">
                        <Textarea
                          id="change-management"
                          value={changeManagementTerms}
                          onChange={(event) => setChangeManagementTerms(event.target.value)}
                          disabled={locked}
                          rows={5}
                        />
                      </FormRow>
                      <FormRow label="Condiciones adicionales" htmlFor="terms">
                        <Textarea
                          id="terms"
                          value={terms}
                          onChange={(event) => setTerms(event.target.value)}
                          disabled={locked}
                          rows={5}
                          placeholder="Vigencia, licencias, garantías u otras condiciones."
                        />
                      </FormRow>
                    </div>
                  </details>
                </section>
              </div>
            ) : null}

            {activeStep === 3 ? (
              <div className="flex flex-col gap-5">
                <MaintenanceOfferEditor
                  offer={maintenanceOptions}
                  selectedPlanId={maintenanceSelectedPlanId}
                  onChange={setMaintenanceOptions}
                  onSelectedPlanChange={setMaintenanceSelectedPlanId}
                  locked={locked}
                />
                <section className="border-border bg-card rounded-xl border p-5">
                  <h2 className="text-base font-semibold">Equipo que verá el cliente</h2>
                  <p className="text-muted-foreground mt-1 text-sm">
                    Selecciona quién aparecerá junto a la propuesta y en el portal del cliente.
                  </p>
                  <div className="mt-3 grid gap-2 sm:grid-cols-2">
                    {teamMembers.map((member) => (
                      <label
                        key={member.id}
                        className="border-border flex cursor-pointer items-center gap-3 rounded-lg border p-3"
                      >
                        <input
                          type="checkbox"
                          checked={teamMemberIds.includes(member.id)}
                          disabled={locked}
                          onChange={(event) =>
                            setTeamMemberIds(
                              event.target.checked
                                ? [...teamMemberIds, member.id]
                                : teamMemberIds.filter((memberId) => memberId !== member.id),
                            )
                          }
                        />
                        <span>
                          <span className="block text-sm font-medium">{member.name}</span>
                          <span className="text-muted-foreground block text-xs">
                            {member.job_title ?? 'Equipo Doscientos'}
                          </span>
                        </span>
                      </label>
                    ))}
                  </div>
                </section>
                <section className="border-primary/20 bg-primary/5 rounded-xl border p-5">
                  <div className="grid gap-3 sm:grid-cols-2">
                    <div className="bg-background rounded-lg p-3">
                      <p className="text-muted-foreground text-xs">Inversión inicial</p>
                      <p className="mt-1 text-lg font-semibold tabular-nums">
                        {formatEUR(proposalTotals.oneTime.total)}
                      </p>
                    </div>
                    {maintenanceOptions.enabled ? (
                      <div className="bg-background rounded-lg p-3">
                        <p className="text-muted-foreground text-xs">Mantenimiento</p>
                        <p className="mt-1 text-lg font-semibold">
                          {selectedMaintenance
                            ? `${selectedMaintenance.name} · ${formatEUR(selectedMaintenance.monthly_price)}/mes`
                            : 'Pendiente de elegir'}
                        </p>
                      </div>
                    ) : null}
                  </div>
                </section>
              </div>
            ) : null}
          </main>

          <aside className="border-border bg-card flex flex-col gap-4 rounded-xl border p-4 xl:sticky xl:top-24">
            <div>
              <p className="text-muted-foreground text-xs font-medium tracking-wide uppercase">
                Resumen comercial
              </p>
              <p className="text-muted-foreground mt-1 text-sm">Se actualiza mientras editas.</p>
            </div>
            <div className="bg-muted/40 rounded-lg p-3">
              <p className="text-muted-foreground text-xs">Inversión inicial · IVA incluido</p>
              <p className="mt-1 text-2xl font-semibold tabular-nums">
                {formatEUR(proposalTotals.oneTime.total)}
              </p>
            </div>
            <div className="flex flex-col gap-2 text-sm">
              <div className="flex items-center justify-between gap-3">
                <span className="text-muted-foreground">Vigencia</span>
                <span className="font-medium">{validUntil || 'Pendiente'}</span>
              </div>
              {maintenanceOptions.enabled ? (
                <div className="flex items-center justify-between gap-3">
                  <span className="text-muted-foreground">Mantenimiento</span>
                  <span className="text-right font-medium">
                    {selectedMaintenance
                      ? `${formatEUR(selectedMaintenance.monthly_price)}/mes`
                      : 'Pendiente'}
                  </span>
                </div>
              ) : null}
              {proposalTotals.monthly.total > 0 ? (
                <div className="flex items-center justify-between gap-3">
                  <span className="text-muted-foreground">Recurrente en partidas</span>
                  <span className="font-medium tabular-nums">
                    {formatEUR(proposalTotals.monthly.total)}/mes
                  </span>
                </div>
              ) : null}
            </div>
            <div className="border-border border-t pt-3">
              <p className="text-muted-foreground mb-2 text-xs font-medium">Completitud</p>
              <div className="flex flex-col gap-2">
                {EDITOR_STEPS.map((step, index) => (
                  <div key={step.label} className="flex items-center gap-2 text-xs">
                    <Check
                      className={`size-3.5 ${stepComplete[index] ? 'text-primary' : 'text-muted-foreground/40'}`}
                      aria-hidden
                    />
                    <span
                      className={stepComplete[index] ? 'text-foreground' : 'text-muted-foreground'}
                    >
                      {step.label}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </aside>
        </div>

        <footer className="border-border bg-background/95 sticky bottom-3 z-20 flex items-center justify-between gap-3 rounded-xl border p-3 shadow-sm backdrop-blur">
          <Button
            type="button"
            variant="outline"
            disabled={activeStep === 0}
            onClick={() => setActiveStep((step) => Math.max(0, step - 1))}
          >
            <ChevronLeft className="size-4" aria-hidden />
            Anterior
          </Button>
          <Button
            type="button"
            disabled={activeStep === EDITOR_STEPS.length - 1 && (locked || saveFeedback.pending)}
            onClick={() => {
              if (activeStep === EDITOR_STEPS.length - 1) {
                void handleSave()
                return
              }
              setActiveStep((step) => Math.min(EDITOR_STEPS.length - 1, step + 1))
            }}
          >
            {activeStep === EDITOR_STEPS.length - 1 ? (
              <>
                <Save className="size-4" aria-hidden />
                {saveFeedback.pending ? 'Guardando…' : 'Guardar y ver propuesta'}
              </>
            ) : (
              <>
                Continuar a {nextStep.label}
                <ChevronRight className="size-4" aria-hidden />
              </>
            )}
          </Button>
        </footer>
      </div>
      <VersionConflictDialog
        open={conflictOpen}
        entityName="propuesta"
        onKeepEditing={() => setConflictOpen(false)}
        onReload={() => {
          setConflictOpen(false)
          router.refresh()
        }}
      />
    </>
  )
}
