import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'

import { DEFAULT_MAINTENANCE_OFFER } from '@/lib/proposals/maintenance'

vi.mock('@/components/finance/line-items-table', () => ({ LineItemsTable: () => null }))
vi.mock('@/components/proposals/maintenance-offer-editor', () => ({
  MaintenanceOfferEditor: () => null,
}))
vi.mock('@/components/proposals/problem-solution-editor', () => ({
  ProblemSolutionEditor: () => null,
}))
vi.mock('@/components/proposals/scope-modules-editor', () => ({ ScopeModulesEditor: () => null }))
vi.mock('../actions', () => ({ setProposalTeamMembers: vi.fn(), updateProposal: vi.fn() }))
vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn(), refresh: vi.fn() }) }))

import { setProposalTeamMembers, updateProposal } from '../actions'
import { ProposalEditor } from './proposal-editor'

const ID = '494d62cb-fd56-4650-b131-9e3a927a20ad'
const saveProposal = vi.mocked(updateProposal)
const saveTeam = vi.mocked(setProposalTeamMembers)
const props = {
  id: ID,
  initialTitle: 'Propuesta inicial',
  initialValidUntil: null,
  initialNotes: null,
  initialContextMarkdown: null,
  initialProblems: [],
  initialSolutions: [],
  initialTerms: null,
  initialScopeModules: [],
  initialDeliverables: null,
  initialAcceptanceCriteria: null,
  initialPaymentSchedule: null,
  initialPaymentPlan: [],
  initialPaymentTerms: null,
  initialChangeManagementTerms: null,
  initialMaintenanceOptions: DEFAULT_MAINTENANCE_OFFER,
  initialMaintenanceSelectedPlanId: null,
  teamMembers: [],
  initialTeamMemberIds: [],
  initialItems: [],
  initialVersion: 1,
  locked: false,
  aiEnabled: false,
  leadId: null,
  autoGenerateDraft: false,
}

describe('ProposalEditor', () => {
  beforeEach(() => {
    saveProposal.mockReset()
    saveTeam.mockReset()
    saveProposal.mockResolvedValue({ ok: true, version: 2 })
    saveTeam.mockResolvedValue({ ok: true })
  })

  it('saves proposal edits and team together when the user returns to the overview', async () => {
    render(<ProposalEditor {...props} />)

    fireEvent.change(screen.getByLabelText('Título'), { target: { value: 'Propuesta revisada' } })
    expect(saveProposal).not.toHaveBeenCalled()

    fireEvent.click(screen.getAllByRole('button', { name: 'Guardar y ver propuesta' })[0]!)

    await waitFor(() =>
      expect(saveProposal).toHaveBeenCalledWith(
        expect.objectContaining({ id: ID, title: 'Propuesta revisada' }),
      ),
    )
    expect(saveTeam).toHaveBeenCalledWith({ proposal_id: ID, member_ids: [] })
  })

  it('persists a proposal without maintenance', async () => {
    render(
      <ProposalEditor
        {...props}
        initialMaintenanceOptions={{ ...DEFAULT_MAINTENANCE_OFFER, enabled: false }}
      />,
    )

    fireEvent.click(screen.getAllByRole('button', { name: 'Guardar y ver propuesta' })[0]!)

    await waitFor(() =>
      expect(saveProposal).toHaveBeenCalledWith(
        expect.objectContaining({
          maintenance_options: expect.objectContaining({ enabled: false }),
          maintenance_selected_plan_id: null,
        }),
      ),
    )
  })

  it('guides the user through the proposal steps', () => {
    render(<ProposalEditor {...props} />)

    expect(screen.getByRole('heading', { name: 'Empieza por lo esencial' })).toBeDefined()
    fireEvent.click(screen.getByRole('button', { name: 'Continuar a Alcance' }))
    expect(screen.getByRole('heading', { name: 'Cuenta la propuesta' })).toBeDefined()

    fireEvent.click(screen.getByRole('button', { name: 'Continuar a Precio' }))
    expect(screen.getByRole('heading', { name: 'Precio de la propuesta' })).toBeDefined()
    expect(screen.getByText('Facturación por plazos')).toBeDefined()

    fireEvent.click(screen.getByRole('button', { name: 'Continuar a Revisión' }))
    expect(screen.getByText('Inversión inicial')).toBeDefined()
    expect(screen.queryByRole('heading', { name: 'Lista para revisar' })).toBeNull()
    expect(
      screen.queryByText(
        'Comprueba el resumen y guarda para volver a la vista de propuesta. Desde allí podrás enviar o marcarla como enviada.',
      ),
    ).toBeNull()
  })
})
