import { Button, Hr, Section, Text } from '@react-email/components'

import { EmailLayout } from './email-layout'

const BRAND = '#2A4227'
const BRAND_LIGHT = '#edf3ec'
const FONT = "'Geist', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"

export type TeamInviteEmailProps = {
  /** Name of the invited person, if known. */
  inviteeName?: string
  /** Invite accept link generated by Supabase auth.admin.generateLink(). */
  inviteUrl: string
  /** Role assigned to the invitee, e.g. "Miembro" */
  roleLabel: string
  /** Absolute base URL of the app (for logo resolution). */
  appUrl: string
}

/**
 * Transactional email sent when a team member is invited to the backoffice.
 *
 * Usage:
 *   const html = await renderEmail(<TeamInviteEmail {...props} />);
 *   await sendEmail({ fromName: "doscientos", fromAlias: "hola", subject: "...", html });
 */
export function TeamInviteEmail({
  inviteeName,
  inviteUrl,
  roleLabel,
  appUrl,
}: TeamInviteEmailProps) {
  const greeting = inviteeName ? `Hola, ${inviteeName.split(' ')[0]}` : 'Hola'

  return (
    <EmailLayout preview="Te han invitado a unirte al equipo de doscientos" appUrl={appUrl}>
      {/* Hero accent band */}
      <Section
        style={{
          backgroundColor: BRAND,
          borderRadius: 10,
          padding: '28px 32px',
          marginBottom: 28,
          textAlign: 'center',
        }}
      >
        <Text style={{ fontFamily: FONT, fontSize: 36, margin: '0 0 8px', lineHeight: 1 }}>👋</Text>
        <Text
          style={{
            fontFamily: FONT,
            fontSize: 22,
            fontWeight: 700,
            color: '#ffffff',
            margin: 0,
            letterSpacing: '-0.02em',
            lineHeight: '28px',
          }}
        >
          Invitación al equipo
        </Text>
      </Section>

      {/* Greeting */}
      <Text style={headingStyle}>{greeting}</Text>
      <Text style={bodyStyle}>
        El equipo de <strong>doscientos</strong> te ha invitado a unirte al backoffice como{' '}
        <strong>{roleLabel}</strong>.
      </Text>
      <Text style={bodyStyle}>
        Haz clic en el botón para activar tu cuenta. Una vez dentro, podrás iniciar sesión con tu
        cuenta de Google.
      </Text>

      {/* CTA */}
      <Button
        href={inviteUrl}
        style={{
          display: 'block',
          width: '100%',
          backgroundColor: BRAND,
          color: '#ffffff',
          fontFamily: FONT,
          fontSize: 15,
          fontWeight: 600,
          textAlign: 'center',
          textDecoration: 'none',
          borderRadius: 8,
          padding: '14px 0',
          boxSizing: 'border-box',
          marginTop: 8,
        }}
      >
        Activar mi cuenta
      </Button>

      {/* Info box */}
      <Section
        style={{
          backgroundColor: BRAND_LIGHT,
          borderRadius: 8,
          padding: '14px 18px',
          marginTop: 24,
        }}
      >
        <Text style={{ ...bodyStyle, color: '#3d6b39', margin: 0, fontSize: 13 }}>
          🔒 Este enlace es de un solo uso y caduca en <strong>72 horas</strong>. Si no esperabas
          esta invitación, puedes ignorar este email.
        </Text>
      </Section>

      <Hr style={{ borderColor: '#e4e4e7', margin: '28px 0 16px' }} />
      <Text style={{ ...bodyStyle, color: '#a1a1aa', fontSize: 12, margin: 0 }}>
        Si el botón no funciona, copia y pega este enlace en tu navegador:
      </Text>
      <Text
        style={{
          ...bodyStyle,
          color: '#a1a1aa',
          fontSize: 11,
          wordBreak: 'break-all',
          marginTop: 4,
        }}
      >
        {inviteUrl}
      </Text>
    </EmailLayout>
  )
}

const headingStyle = {
  fontFamily: FONT,
  fontSize: 20,
  fontWeight: 700,
  color: '#111111',
  margin: '0 0 12px',
  letterSpacing: '-0.02em',
}

const bodyStyle = {
  fontFamily: FONT,
  fontSize: 15,
  color: '#3f3f46',
  lineHeight: '24px',
  margin: '0 0 16px',
}
